resources:
- repo: self

variables:
  ArtifactsDirectoryName: 'artifacts'
  BuildConfiguration: 'Debug'
  BuildPlatform: 'Any CPU'
  DotNetCore3Version: '3.x'
  DotNetCore5Version: '5.x'
  MSBuildArgs: '"/p:Platform=$(BuildPlatform)" "/p:Configuration=$(BuildConfiguration)" "/BinaryLogger:$(Build.SourcesDirectory)\$(ArtifactsDirectoryName)\msbuild.binlog"'
  SignType: 'Test'

trigger:
  batch: 'true'
  branches:
    include:
    - 'master'
    - 'rel/*'
  paths:
    exclude:
    - '*.md'
pr:
  branches:
    include:
    - 'master'
    - 'rel/*'
  paths:
    exclude:
    - '*.md'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  pool:
    vmImage: windows-latest
  steps:
  - task: UseDotNet@2
    displayName: 'Install .NET Core $(DotNetCore3Version)'
    inputs:
      version: '$(DotNetCore3Version)'

  - task: UseDotNet@2
    displayName: 'Install .NET Core $(DotNetCore5Version)'
    inputs:
      version: '$(DotNetCore5Version)'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    displayName: 'Build Solution'
    inputs:
      command: 'build'
      projects: 'MSBuildSdks.sln'
      arguments: '$(MSBuildArgs)'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET 5)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --framework net5.0 "/restore:false"'
      testRunTitle: '.NET v5.0'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET Framework)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --framework net472 "/restore:false"'
      testRunTitle: '.NET Framework v4.7.2'

  - task: DotNetCoreCLI@2
    displayName: 'Run Unit Tests (.NET Core)'
    inputs:
      command: 'test'
      arguments: '--no-restore --no-build --framework netcoreapp3.1 "/restore:false"'
      testRunTitle: '.NET Core v3.1'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifacts'
    inputs:
      PathtoPublish: '$(ArtifactsDirectoryName)'
      ArtifactName: $(ArtifactsDirectoryName)
    condition: always()