resources:
- repo: self

variables:
  ArtifactsDirectoryName: 'artifacts'
  BuildConfiguration: 'Release'
  BuildPlatform: 'Any CPU'
  DotNetCore3Version: '3.x'
  DotNetCore5Version: '5.x'
  MSBuildArgs: '"/clp:v=n" "/p:Platform=$(BuildPlatform)" "/p:Configuration=$(BuildConfiguration)" "/BinaryLogger:$(Build.SourcesDirectory)\$(ArtifactsDirectoryName)\msbuild.binlog"'
  SignType: 'Real'

trigger:
  batch: true
  branches:
    include:
    - 'master'
    - 'refs/tags/*'
  paths:
    exclude:
    - '*.md'

pr:
  branches:
    include:
    - master
    - 'rel/*'
  paths:
    exclude:
    - '*.md'

stages:
- stage:
  displayName: 'Build'
  jobs:
  - job: Build
    displayName: 'Build'
    pool:
      name: VSEng-MicroBuildVS2019
    steps:
    - script: 'echo ##vso[task.setvariable variable=SignType;]Real'
      displayName: 'Set SignType to Real for tagged commits'
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/Microsoft.Build'))

    - task: UseDotNet@2
      displayName: 'Install .NET Core $(DotNetCore3Version)'
      inputs:
        version: '$(DotNetCore3Version)'

    - task: UseDotNet@2
      displayName: 'Install .NET Core $(DotNetCore5Version)'
      inputs:
        version: '$(DotNetCore5Version)'
        includePreviewVersions: true

    - task: MicroBuildSigningPlugin@1
      displayName: 'Install MicroBuild Signing Plugin'
      inputs:
        signType: '$(SignType)'
        zipSources: false

    - task: DotNetCoreCLI@2
      displayName: 'Build Solution'
      inputs:
        command: 'build'
        projects: 'MSBuildSdks.sln'
        arguments: '$(MSBuildArgs)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(ArtifactsDirectoryName)'
        ArtifactName: $(ArtifactsDirectoryName)
      condition: always()