<Project>
  <PropertyGroup>
    <DefaultItemExcludes>*log</DefaultItemExcludes>
    <MSBuildTreatWarningsAsErrors>true</MSBuildTreatWarningsAsErrors>
    <LangVersion>Latest</LangVersion>
    <EnableDefaultNoneItems>false</EnableDefaultNoneItems>
    <NoWarn>$(NoWarn);NU5128;SA0001</NoWarn>
    <!--
      Disabling static graph restore due to a bug related to NuGetAuditSuppress.
      See: https://github.com/NuGet/Home/issues/14300
    -->
    <RestoreUseStaticGraphEvaluation>false</RestoreUseStaticGraphEvaluation>
    <RestoreSerializeGlobalProperties>true</RestoreSerializeGlobalProperties>
    <UseArtifactsOutput>true</UseArtifactsOutput>
    <IsTestProject Condition="$(MSBuildProjectName.EndsWith('UnitTests'))">true</IsTestProject>
    <IsPackable Condition="'$(IsTestProject)' != 'true'">true</IsPackable>

    <!-- Suppress spam about using a preview version of .NET -->
    <SuppressNETCoreSdkPreviewMessage>true</SuppressNETCoreSdkPreviewMessage>
  </PropertyGroup>

  <ItemGroup Condition="'$(IsTestProject)' == 'true' And '$(TargetFramework)' == 'net472'">
    <!-- MSBuild.ProjectCreation loads MSBuild's runtime closure from Visual Studio. -->
    <PackageReference Include="System.Threading.Tasks.Extensions"
                      ExcludeAssets="runtime"
                      PrivateAssets="all" />
  </ItemGroup>

  <!-- Symbols and Source Link -->
  <PropertyGroup>
    <DebugType>embedded</DebugType>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>
</Project>